
package newpackage;

public class NewJFrame extends javax.swing.JFrame {

    BListe l;
    public NewJFrame() {
        initComponents();
        l = new BListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        basaEkle = new javax.swing.JButton();
        bastanSil = new javax.swing.JButton();
        sonaEkle = new javax.swing.JButton();
        sondanSil = new javax.swing.JButton();
        elemanıSil = new javax.swing.JButton();
        listeyiYazdır = new javax.swing.JButton();
        siraliEkle = new javax.swing.JButton();
        elemanAra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sayı:");

        basaEkle.setText("Başa Ekle");
        basaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basaEkleActionPerformed(evt);
            }
        });

        bastanSil.setText("Baştan Sil");
        bastanSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bastanSilActionPerformed(evt);
            }
        });

        sonaEkle.setText("Sona Ekle");
        sonaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonaEkleActionPerformed(evt);
            }
        });

        sondanSil.setText("Sondan Sil");
        sondanSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sondanSilActionPerformed(evt);
            }
        });

        elemanıSil.setText("Sil");
        elemanıSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemanıSilActionPerformed(evt);
            }
        });

        listeyiYazdır.setText("Yazdır");
        listeyiYazdır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeyiYazdırActionPerformed(evt);
            }
        });

        siraliEkle.setText("Sıralı Ekle ");
        siraliEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siraliEkleActionPerformed(evt);
            }
        });

        elemanAra.setText("Ara");
        elemanAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemanAraActionPerformed(evt);
            }
        });

        jLabel2.setText("Liste:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elemanıSil)
                            .addComponent(listeyiYazdır))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basaEkle)
                            .addComponent(sonaEkle)
                            .addComponent(siraliEkle))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elemanAra)
                            .addComponent(sondanSil)
                            .addComponent(bastanSil))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basaEkle)
                    .addComponent(bastanSil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonaEkle)
                    .addComponent(sondanSil)
                    .addComponent(elemanıSil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listeyiYazdır)
                    .addComponent(siraliEkle)
                    .addComponent(elemanAra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basaEkleActionPerformed
        int sayi = Integer.parseInt(jTextField1.getText());
        Eleman yeni = new Eleman(sayi);
        l.basaekle(yeni);
        jLabel2.setText(l.listele());
        jTextField1.setText("");

    }//GEN-LAST:event_basaEkleActionPerformed

    private void bastanSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bastanSilActionPerformed
         Eleman sonuc = l.bastansil();
        if(sonuc != null)
            jLabel2.setText(l.listele());
        else
            jLabel2.setText("Liste boş ");

    }//GEN-LAST:event_bastanSilActionPerformed

    private void elemanıSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemanıSilActionPerformed
        int aranan = Integer.parseInt(jTextField1.getText());
        Eleman sonuc = l.elemansil(aranan);
        if(sonuc != null) 
            jLabel2.setText(l.listele());
        else
            jLabel2.setText("Silinecek eleman bulunamadı");
        jTextField1.setText("");

    }//GEN-LAST:event_elemanıSilActionPerformed

    private void sonaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonaEkleActionPerformed
         int sayi = Integer.parseInt(jTextField1.getText());
        Eleman yeni = new Eleman(sayi);
        l.sonaekle(yeni);
        jLabel2.setText(l.listele());
        jTextField1.setText("");

    }//GEN-LAST:event_sonaEkleActionPerformed

    private void sondanSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sondanSilActionPerformed
         Eleman sonuc = l.sondansil();
        if(sonuc != null)
            jLabel2.setText(l.listele());
        else
            jLabel2.setText("Liste boş ");

    }//GEN-LAST:event_sondanSilActionPerformed

    private void listeyiYazdırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeyiYazdırActionPerformed
        Eleman tmp = l.bas;
        jLabel2.setText(l.yazdir(tmp));

    }//GEN-LAST:event_listeyiYazdırActionPerformed

    private void siraliEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siraliEkleActionPerformed
         int icerik = Integer.parseInt(jTextField1.getText());
        Eleman yeni = new Eleman(icerik);
        l.siraliekle(yeni);
        jLabel2.setText(l.listele());
        jTextField1.setText("");

    }//GEN-LAST:event_siraliEkleActionPerformed

    private void elemanAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemanAraActionPerformed
        int aranan = Integer.parseInt(jTextField1.getText());
        Eleman sonuc = l.listeara(aranan);
        if(sonuc != null) {
            if(l.yerBul(aranan) != -1)
                jLabel2.setText("Aranan elemanın yeri: " + l.yerBul(aranan));
        }
        else
            jLabel2.setText("Aranan eleman listede yok");
        jTextField1.setText("");

    }//GEN-LAST:event_elemanAraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basaEkle;
    private javax.swing.JButton bastanSil;
    private javax.swing.JButton elemanAra;
    private javax.swing.JButton elemanıSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton listeyiYazdır;
    private javax.swing.JButton siraliEkle;
    private javax.swing.JButton sonaEkle;
    private javax.swing.JButton sondanSil;
    // End of variables declaration//GEN-END:variables
}
